version: '3.7'

services:
  db:
    build: ./dev/db
    container_name: wpdb
    env_file:
      - ./dev/db/wpdb.env
    image: wpdb:1.0
    networks:
      wp-network:
        aliases:
          - wpdb-net
    restart: always
    volumes:
      - source: wpdb-volume
        target: /var/lib/mysql
        type: volume

  wp:
    build: ./dev/wp
    container_name: wp
    depends_on:
      - db
    env_file:
      - ./dev/wp/wp.env
    image: wp:1.0
    networks:
      wp-network:
        aliases:
          - wp-net
    ports:
      - published: '8000'
        target: '80'
    restart: always
    volumes:
      - source: .
        target: /var/www/html/wp-content/themes/gulppress
        type: bind

networks:
  wp-network:
    name: wp-network
    driver: bridge
    ipam:
      config:
        - subnet: 168.10.10.0/24

volumes:
  wpdb-volume:
    name: wpdb-volume
